project:
  type: website
  output-dir: docs

website:
  sidebar: false
  navbar:
    left:
      - href: index.qmd
        text: Title and authors
      - about.qmd
      - ZosteropsMaps.qmd
      - Summary_Sanger.qmd
      - Zosterops_StarBEAST2.qmd
      - ZosteropsBPP.qmd
      - ZosteropsSNPs_analysis.qmd
      - Zosterops_SNPFst.qmd
      - Zosterops_SVDQ.qmd
      - ZosteropsMorphometrics.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    grid:
      sidebar-width: 0px
      body-width: 1200px
      
editor: visual